const game=document.querySelector('#game'),canvas=document.querySelector('#map'),ctx=canvas.getContext('2d'),dialog=document.querySelector('#minigame'),content=document.querySelector('#minigame-content'),message=document.querySelector('#message'),status=document.querySelector('#system-status');
const S=24,OX=130,OY=200,done=new Set();let player={x:3,y:11},active=null;
const rooms=[
 {id:1,name:'РЕМОНТНЫЙ ОТСЕК',task:'power',x:2,y:7,w:6,h:6,tx:5,ty:10},
 {id:2,name:'ЭНЕРГООТСЕК',task:'pump',x:8,y:7,w:6,h:6,tx:11,ty:10},
 {id:3,name:'ГИДРОАКУСТИКА',task:'sonar',x:14,y:7,w:6,h:6,tx:17,ty:10},
 {id:4,name:'КАПИТАНСКИЙ МОСТИК',task:'code',x:20,y:7,w:6,h:6,tx:23,ty:10},
 {id:5,name:'КАЮТ-КОМПАНИЯ',task:'relay',x:26,y:7,w:6,h:6,tx:29,ty:10},
 {id:6,name:'КАМБУЗ / ОСУШЕНИЕ',task:'pump',x:32,y:7,w:6,h:6,tx:35,ty:10},
 {id:7,name:'ТРЮМ СВЯЗИ',task:'code',x:38,y:7,w:6,h:6,tx:41,ty:10}
];
const corridors=[];
const walk=new Set(),key=(x,y)=>x+','+y;
function add(x,y,w,h){for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)walk.add(key(i,j));}
rooms.forEach(r=>add(r.x,r.y,r.w,r.h));corridors.forEach(c=>add(...c));
function roomAt(x,y){return rooms.find(r=>x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h)}
function say(t){message.textContent='РМ-01: '+t}
function reachable(x,y){const r=roomAt(x,y);return walk.has(key(x,y))&&(!r||r.id<=done.size+1)}
function draw(){
 const X=x=>OX+x*S,Y=y=>OY+y*S;
 ctx.clearRect(0,0,1400,780);ctx.fillStyle='#06151b';ctx.fillRect(0,0,1400,780);
 ctx.strokeStyle='#143d46';ctx.lineWidth=1;for(let y=0;y<780;y+=12){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1400,y);ctx.stroke()}
 ctx.strokeStyle='#315f68';ctx.lineWidth=6;ctx.strokeRect(24,20,1352,730);ctx.strokeStyle='#173e47';ctx.lineWidth=2;ctx.strokeRect(40,35,1320,700);
 ctx.fillStyle='#6f9ca1';ctx.font='17px VT323';['КЛАСС:  ДИЗЕЛЬ-ЭЛЕКТРИЧЕСКАЯ ПЛ','ПРОЕКТ:  РМ-01','ДЛИНА:   74.0 М','ЭКИПАЖ:  22 ЧЕЛ.','СТАТУС:  ЧАСТИЧНО ВОССТАНОВЛЕНА'].forEach((t,i)=>ctx.fillText(t,64,82+i*20));
 ctx.strokeStyle='#315f68';ctx.lineWidth=1;ctx.strokeRect(955,55,410,150);ctx.fillStyle='#8ebbb9';ctx.font='16px VT323';ctx.fillText('ВИД: ПРАВЫЙ БОРТ',975,78);ctx.strokeStyle='#76e6c5';ctx.beginPath();ctx.ellipse(1090,132,100,18,0,0,Math.PI*2);ctx.stroke();ctx.moveTo(1170,132);ctx.lineTo(1200,117);ctx.lineTo(1200,147);ctx.stroke();
 [['#76e6c5','СИСТЕМА ОНЛАЙН'],['#f7bd54','ВЫБРАННЫЙ ОТСЕК'],['#ef6b5d','СИСТЕМА ЗАБЛОКИРОВАНА'],['#315f68','НЕТ ПИТАНИЯ']].forEach((v,i)=>{ctx.strokeStyle=v[0];ctx.lineWidth=3;ctx.strokeRect(1208,72+i*28,18,18);ctx.fillStyle='#7fa4a5';ctx.fillText(v[1],1243,87+i*28)});
 ctx.beginPath();ctx.moveTo(78,495);ctx.bezierCurveTo(92,385,175,343,325,342);ctx.lineTo(1095,342);ctx.bezierCurveTo(1195,347,1260,382,1305,430);ctx.lineTo(1350,490);ctx.lineTo(1305,550);ctx.bezierCurveTo(1260,598,1195,633,1095,638);ctx.lineTo(325,638);ctx.bezierCurveTo(175,637,92,595,78,495);ctx.closePath();ctx.fillStyle='#08242a';ctx.fill();ctx.strokeStyle='#83e7da';ctx.lineWidth=3;ctx.stroke();
 ctx.beginPath();ctx.moveTo(570,342);ctx.lineTo(590,270);ctx.lineTo(760,270);ctx.lineTo(790,342);ctx.moveTo(610,270);ctx.lineTo(610,205);ctx.lineTo(630,205);ctx.lineTo(630,270);ctx.moveTo(680,270);ctx.lineTo(680,185);ctx.lineTo(700,185);ctx.lineTo(700,270);ctx.moveTo(745,270);ctx.lineTo(745,220);ctx.lineTo(765,220);ctx.lineTo(765,270);ctx.strokeStyle='#76e6c5';ctx.lineWidth=2;ctx.stroke();
 for(let x=150;x<1240;x+=38){ctx.strokeStyle='#1b5960';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,365);ctx.lineTo(x,615);ctx.stroke()}
 rooms.forEach(r=>{const unlocked=r.id<=done.size+1,fixed=done.has(r.id),selected=unlocked&&!fixed;const x=X(r.x),y=Y(r.y),w=r.w*S,h=r.h*S;ctx.fillStyle=fixed?'#123b3d':unlocked?'#0c2a31':'#09191f';ctx.fillRect(x,y,w,h);ctx.strokeStyle=selected?'#f7bd54':unlocked?'#76e6c5':'#31565e';ctx.lineWidth=selected?4:2;ctx.strokeRect(x,y,w,h);if(selected){ctx.shadowColor='#f7bd54';ctx.shadowBlur=18;ctx.strokeRect(x+4,y+4,w-8,h-8);ctx.shadowBlur=0}ctx.fillStyle=unlocked?'#c2e7df':'#5c787a';ctx.font='18px VT323';const words=r.name.split(' ');ctx.fillText(('0'+r.id).slice(-2),x+13,y+28);words.slice(0,2).forEach((word,i)=>ctx.fillText(word,x+13,y+50+i*19));for(let k=0;k<4;k++){ctx.strokeStyle='#205058';ctx.lineWidth=1;ctx.strokeRect(x+15+k*28,y+h-45,19,25)}ctx.fillStyle=fixed?'#76e6c5':'#ef6b5d';ctx.fillRect(X(r.tx)-10,Y(r.ty)-10,20,20);ctx.strokeStyle='#e2fff2';ctx.lineWidth=2;ctx.strokeRect(X(r.tx)-12,Y(r.ty)-12,24,24)});
 rooms.slice(1).forEach(r=>{const boundary=X(r.x);ctx.fillStyle=r.id<=done.size+1?'#76e6c5':'#ef6b5d';ctx.fillRect(boundary-4,Y(9),8,58);ctx.fillStyle='#7fa4a5';ctx.font='12px VT323';ctx.fillText(r.id<=done.size+1?'ШЛЮЗ':'LOCK',boundary-14,Y(12)+15)});
 ctx.fillStyle='#76e6c5';ctx.fillRect(X(player.x)+4,Y(player.y)+6,16,15);ctx.strokeStyle='#e2fff2';ctx.lineWidth=2;ctx.strokeRect(X(player.x)+4,Y(player.y)+6,16,15);ctx.fillStyle='#f7bd54';ctx.fillRect(X(player.x)+14,Y(player.y)+12,4,4);
 if(active){ctx.strokeStyle='#f7bd54';ctx.lineWidth=2;ctx.strokeRect(X(active.tx-1),Y(active.ty-1),S*2,S*2)}
 ctx.strokeStyle='#315f68';ctx.lineWidth=1;ctx.strokeRect(58,665,200,80);ctx.strokeRect(1170,665,190,80);ctx.fillStyle='#7fa4a5';ctx.font='17px VT323';['ГЛУБИНА:   127 М','КУРС:      092°','СКОРОСТЬ:  0 УЗЛ.'].forEach((t,i)=>ctx.fillText(t,78,690+i*19));['ДАТЧИКИ:   НОРМА','КОРПУС:    ЦЕЛ','ПИТАНИЕ:   '+done.size+' / 7'].forEach((t,i)=>ctx.fillText(t,1190,690+i*19));
}
function update(){const r=roomAt(player.x,player.y);active=r&&!done.has(r.id)&&Math.abs(player.x-r.tx)+Math.abs(player.y-r.ty)<=1?r:null;draw();}
function finish(id){done.add(id);status.textContent='СИСТЕМЫ: '+done.size+' / 7';dialog.close();say(id===7?'СИГНАЛ ПЕРЕДАН. В ГЛУБИНЕ ЕСТЬ ОТВЕТ.':'Система восстановлена. Открыт следующий шлюз.');game.focus();update()}
function mount(title,copy,hint,body){content.innerHTML='<button class="hint">?</button><h2 class="mini-title">'+title+'</h2><p class="mini-copy">'+copy+'</p><div class="hint-box"></div>'+body;content.querySelector('.hint').onclick=()=>content.querySelector('.hint-box').textContent='ПОДСКАЗКА: '+hint;}
function power(id){
 const symbols=['◉','⚙','◆','☼','✦','◈','☍','✚'],deck=[...symbols,...symbols].sort(()=>Math.random()-.5),open=Array(16).fill(false),matched=Array(16).fill(false);let first=null,scanning=false,scanTimer,scanInterval;
 mount('ЩИТ ПИТАНИЯ','Память щита: найдите восемь пар символов. После запуска сканер на 10 секунд покажет всю схему.','Нажмите «СБРОС / СКАН» в любой момент: все символы снова откроются на 10 секунд.','<div class="memory-grid">'+deck.map((_,i)=>'<button class="memory-card" data-i="'+i+'">?</button>').join('')+'</div><div class="mini-status">СКАНЕР ГОТОВ</div><button class="reset">СБРОС / СКАН: 10 СЕК.</button>');
 const cards=[...content.querySelectorAll('.memory-card')],miniStatus=content.querySelector('.mini-status');
 const draw=()=>cards.forEach((b,i)=>{const visible=scanning||open[i]||matched[i];b.textContent=visible?deck[i]:'?';b.classList.toggle('open',visible);b.classList.toggle('matched',matched[i]);b.disabled=scanning||matched[i]});
 const scan=()=>{clearTimeout(scanTimer);clearInterval(scanInterval);scanning=true;first=null;open.fill(false);let left=10;miniStatus.textContent='СКАНИРОВАНИЕ: '+left+' СЕК.';draw();scanInterval=setInterval(()=>{left--;miniStatus.textContent='СКАНИРОВАНИЕ: '+left+' СЕК.'},1000);scanTimer=setTimeout(()=>{clearInterval(scanInterval);scanning=false;miniStatus.textContent='НАЙДИТЕ ПАРЫ';draw()},10000)};
 cards.forEach(b=>b.onclick=()=>{if(scanning)return;const i=+b.dataset.i;if(open[i]||matched[i])return;open[i]=true;draw();if(first===null){first=i;miniStatus.textContent='ВЫБЕРИТЕ ВТОРУЮ КАРТОЧКУ';return}const other=first;first=null;if(deck[i]===deck[other]){matched[i]=matched[other]=true;open[i]=open[other]=false;miniStatus.textContent='ПАРА НАЙДЕНА';draw();if(matched.every(Boolean))finish(id)}else{miniStatus.textContent='НЕ ПАРА';setTimeout(()=>{open[i]=open[other]=false;miniStatus.textContent='НАЙДИТЕ ПАРЫ';draw()},650)}});
 content.querySelector('.reset').onclick=scan;scan();
}
function pump(id){const directions=['ВНИЗ','ВЛЕВО','ВВЕРХ','ВПРАВО'],r=[2,1,3,0];mount(id===6?'ОСУШИТЕЛЬНЫЙ НАСОС':'НАСОС № 4','Поверните каждый клапан в положение, указанное в схеме.','Цель слева направо: ВНИЗ → ВЛЕВО → ВВЕРХ → ВПРАВО. Нажатие переключает положение по этому кругу.','<div class="flow-target">ЦЕЛЬ: <b>ВНИЗ</b> → <b>ВЛЕВО</b> → <b>ВВЕРХ</b> → <b>ВПРАВО</b></div><div class="pipe-grid">'+r.map((v,i)=>'<button class="pipe-cell" data-i="'+i+'"><small>КЛАПАН '+(i+1)+'</small><strong>'+directions[v]+'</strong></button>').join('')+'</div>');content.querySelectorAll('.pipe-cell').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;r[i]=(r[i]+1)%4;b.querySelector('strong').textContent=directions[r[i]];if(r.every((v,i)=>v===i))finish(id)})}
function sonar(id){
 let sequence=[],input=[],playing=false,timers=[];
 mount('ГИДРОАКУСТИКА','Прослушайте и повторите шесть импульсов. Нажимайте на большие кнопки «ИМПУЛЬ».','Кнопка «НОВЫЙ СИГНАЛ» каждый раз создаёт другую комбинацию. Пока индикаторы мигают, дождитесь окончания передачи.','<div class="sequence">'+[0,1,2,3].map(i=>'<button class="tone tone-'+i+'" data-i="'+i+'" aria-label="Импульс '+(i+1)+'"><small>ИМПУЛЬ</small><strong>'+(i+1)+'</strong></button>').join('')+'</div><div class="mini-status">ГОТОВ К ПЕРЕДАЧЕ</div><button class="replay">НОВЫЙ СИГНАЛ</button>');
 const tones=[...content.querySelectorAll('.tone')],miniStatus=content.querySelector('.mini-status');
 const later=(fn,ms)=>timers.push(setTimeout(fn,ms));
 function playNew(){timers.forEach(clearTimeout);timers=[];sequence=Array.from({length:6},()=>Math.floor(Math.random()*4));input=[];playing=true;tones.forEach(t=>t.classList.remove('flash'));miniStatus.textContent='СЛУШАЙТЕ…';let n=0;const next=()=>{if(n===sequence.length){playing=false;miniStatus.textContent='ПОВТОРИТЕ СИГНАЛ';return}const tone=tones[sequence[n++]];tone.classList.add('flash');later(()=>{tone.classList.remove('flash');later(next,170)},420)};later(next,350)}
 content.querySelector('.replay').onclick=playNew;
 tones.forEach(b=>b.onclick=()=>{if(playing){miniStatus.textContent='ДОЖДИТЕСЬ КОНЦА ПЕРЕДАЧИ';return}const value=+b.dataset.i;input.push(value);b.classList.add('flash');later(()=>b.classList.remove('flash'),160);if(value!==sequence[input.length-1]){input=[];miniStatus.textContent='ОШИБКА. ЗАПРОСИТЕ НОВЫЙ СИГНАЛ.'}else if(input.length===sequence.length)finish(id);else miniStatus.textContent='ПРИНЯТО: '+input.length+' / '+sequence.length});
 playNew();
}
function code(id){const answer=id===4?'731':'407';let typed='';mount(id===4?'КАПИТАНСКИЙ МОСТИК':'ТРЮМ СВЯЗИ','Введите код доступа на терминале.','Код написан в самой задаче: для мостика — номер каюты 7, палубы 3, поста 1. Для трюма — сектор 4, ячейка 0, канал 7.','<div class="choices">'+[0,1,2,3,4,7].map(n=>'<button class="choice" data-n="'+n+'">'+n+'</button>').join('')+'</div><div class="mini-status">КОД: ———</div>');content.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{typed+=b.dataset.n;content.querySelector('.mini-status').textContent='КОД: '+typed;if(typed.length===3){if(typed===answer)finish(id);else {content.querySelector('.mini-status').textContent='НЕВЕРНО. СБРОС.';typed=''}}})}
function relay(id){const correct=[2,0,3,1],input=[];mount('КАЮТ-КОМПАНИЯ','Перезапустите аварийное освещение: выберите четыре реле по порядку.','Слева направо лампы мигают: третья, первая, четвёртая, вторая.','<div class="choices">'+[0,1,2,3].map(n=>'<button class="choice" data-n="'+n+'">'+(n+1)+'</button>').join('')+'</div><div class="mini-status">ОЧЕРЕДЬ РЕЛЕ</div>');content.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{input.push(+b.dataset.n);if(input.at(-1)!==correct[input.length-1]){input.length=0;content.querySelector('.mini-status').textContent='СБРОС ЦЕПИ'}else if(input.length===4)finish(id)})}
function open(r){({power,pump,sonar,code,relay})[r.task](r.id);dialog.showModal()}
window.addEventListener('keydown',e=>{if(dialog.open){if(e.key==='Escape')dialog.close();return}const d={ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0],ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1]}[e.key];if(d){e.preventDefault();let x=player.x+d[0],y=player.y+d[1];if(reachable(x,y))player={x,y};else say('Здесь сплошная переборка или закрытый шлюз.');update()}if((e.key==='e'||e.key==='E')&&active)open(active);if(e.key==='r'||e.key==='R')say(active?'ЦЕЛЬ: '+active.name+'. Подлетите к центральному терминалу и нажмите E.':'ЦЕЛЬ: найдите красный терминал в доступном отсеке.');});
document.querySelector('#close-game').onclick=()=>dialog.close();game.addEventListener('click',()=>game.focus());game.focus();update();
