const game=document.querySelector('#game'),drone=document.querySelector('#drone'),prompt=document.querySelector('#prompt'),message=document.querySelector('#message'),status=document.querySelector('#system-status'),dialog=document.querySelector('#minigame'),content=document.querySelector('#minigame-content'),terminals=[...document.querySelectorAll('.terminal')];
let position=12,altitude=8,repaired=new Set(),activeTerminal=null;
const say=text=>message.textContent='СИСТЕМА РМ-01: '+text;
function update(){drone.style.left=position+'%';drone.style.bottom=altitude+'%';activeTerminal=terminals.find(t=>!t.closest('.locked')&&!repaired.has(t.dataset.room)&&Math.abs((+t.dataset.room*33-17)-position)<9&&Math.abs(altitude-38)<12);prompt.classList.toggle('hidden',!activeTerminal)}
function move(delta){const next=Math.max(4,Math.min(95,position+delta));const gate=[{x:33.33,room:'1',name:'ШЛЮЗ 01'},{x:66.66,room:'2',name:'ШЛЮЗ 02'}].find(d=>!repaired.has(d.room)&&((position<d.x&&next>=d.x-1.4)||(position>d.x&&next<=d.x+1.4)));if(gate){say(gate.name+': ЗАБЛОКИРОВАН. ВОССТАНОВИТЕ СИСТЕМУ В ТЕКУЩЕМ ОТСЕКЕ.');return}position=next}
function repair(room){repaired.add(room);const el=document.querySelector('#room-'+room);el.classList.remove('locked');el.classList.add('fixed');el.querySelector('small').textContent='НОРМА';if(room==='1'||room==='2'){const door=document.querySelector(room==='1'?'.door-one':'.door-two');door.classList.add('open');door.querySelector('.door-sign').innerHTML='ШЛЮЗ 0'+room+'<br>ОТКРЫТ'}status.textContent='СИСТЕМЫ: '+repaired.size+' / 3';say(({1:'ЩИТ ПИТАНИЯ ВОССТАНОВЛЕН. ШЛЮЗ 01 ОТКРЫТ.',2:'НАСОС № 4 ЗАПУЩЕН. ШЛЮЗ 02 ОТКРЫТ.',3:'СОНАР АКТИВЕН. В ГЛУБИНЕ ОБНАРУЖЕН СЛАБЫЙ ОТВЕТНЫЙ СИГНАЛ...'})[room]);dialog.close();game.focus();update()}
function power(){const start=[1,0,1,0,0,1,1,0,1,1,0,1,0,1,0,1];let cells=[...start];content.innerHTML='<h2 class="mini-title">ЩИТ ПИТАНИЯ</h2><p class="mini-copy">Калибровка 4×4: касание переключает ячейку и четыре соседние. Зажгите весь контур.</p><div class="grid">'+cells.map((_,i)=>'<button class="cell" data-cell="'+i+'"></button>').join('')+'</div><div class="mini-status">НАЙДИТЕ ПОСЛЕДОВАТЕЛЬНОСТЬ ПЕРЕКЛЮЧЕНИЙ</div><button class="reset">СБРОСИТЬ КАЛИБРОВКУ</button>';const draw=()=>content.querySelectorAll('.cell').forEach((b,i)=>{b.textContent=cells[i]?'●':'×';b.classList.toggle('lit',!!cells[i])});const flip=i=>{if(i>=0&&i<16)cells[i]=cells[i]?0:1};content.querySelectorAll('.cell').forEach(b=>b.onclick=()=>{const i=+b.dataset.cell;flip(i);if(i%4)flip(i-1);if(i%4<3)flip(i+1);flip(i-4);flip(i+4);draw();if(cells.every(Boolean))repair('1')});content.querySelector('.reset').onclick=()=>{cells=[...start];draw()};draw()}
function pump(){const shapes=['╹','╺','╻','╸'],r=[2,1,3,0];content.innerHTML='<h2 class="mini-title">НАСОС № 4</h2><p class="mini-copy">Поверните клапаны, чтобы пустить давление по контуру.</p><div class="pipe-grid">'+r.map((v,i)=>'<button class="pipe-cell" data-pipe="'+i+'">'+shapes[v]+'</button>').join('')+'</div><div class="mini-status">СОВМЕСТИТЕ ВСЕ КЛАПАНЫ</div>';content.querySelectorAll('.pipe-cell').forEach(b=>b.onclick=()=>{const i=+b.dataset.pipe;r[i]=(r[i]+1)%4;b.textContent=shapes[r[i]];if(r.every((v,i)=>v===i))repair('2')})}
function sonar(){const p=[0,2,1,3,1,0],input=[];content.innerHTML='<h2 class="mini-title">ГИДРОАКУСТИКА</h2><p class="mini-copy">Повторите шесть импульсов. Сонар помнит чужой сигнал.</p><div class="sequence">'+[0,1,2,3].map(i=>'<button class="tone" data-tone="'+i+'"></button>').join('')+'</div><div class="mini-status">СЛУШАЙТЕ...</div>';const tones=[...content.querySelectorAll('.tone')];let ix=0;const play=()=>{if(ix>=p.length){content.querySelector('.mini-status').textContent='ПОВТОРИТЕ ПОСЛЕДОВАТЕЛЬНОСТЬ';return}tones[p[ix]].classList.add('flash');setTimeout(()=>{tones[p[ix]].classList.remove('flash');ix++;setTimeout(play,180)},420)};setTimeout(play,500);tones.forEach(t=>t.onclick=()=>{if(ix<p.length)return;input.push(+t.dataset.tone);t.classList.add('flash');setTimeout(()=>t.classList.remove('flash'),130);if(input.at(-1)!==p[input.length-1]){content.querySelector('.mini-status').textContent='СИГНАЛ ИСКАЖЁН. ЕЩЁ РАЗ.';setTimeout(sonar,700)}else if(input.length===p.length)repair('3')})}
function open(task){({power,pump,sonar})[task]();dialog.showModal()}
window.addEventListener('keydown',e=>{if(dialog.open){if(e.key==='Escape')dialog.close();return}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key))e.preventDefault();if(['ArrowLeft','a','A'].includes(e.key)){move(-2);drone.className='drone facing-left'}if(['ArrowRight','d','D'].includes(e.key)){move(2);drone.className='drone facing-right'}if(['ArrowUp','w','W',' '].includes(e.key)){altitude=Math.min(78,altitude+7);drone.classList.add('thrusting')}if(['ArrowDown','s','S'].includes(e.key)){altitude=Math.max(8,altitude-7);drone.classList.add('thrusting')}if((e.key==='e'||e.key==='E')&&activeTerminal)open(activeTerminal.dataset.task);update();setTimeout(()=>drone.classList.remove('thrusting'),140)});
document.querySelector('#close-game').onclick=()=>dialog.close();terminals.forEach(t=>t.onclick=()=>{say('ПОДЛЕТИТЕ К ТЕРМИНАЛУ И НАЖМИТЕ E.');game.focus()});game.addEventListener('click',()=>game.focus());setTimeout(()=>{say('ПИТАНИЕ: АВАРИЙНЫЙ РЕЖИМ. ПОДНИМИТЕСЬ К ЩИТУ И НАЖМИТЕ E.');game.focus()},900);update();
