const game=document.querySelector('#game'),canvas=document.querySelector('#map'),ctx=canvas.getContext('2d'),dialog=document.querySelector('#minigame'),content=document.querySelector('#minigame-content'),message=document.querySelector('#message'),status=document.querySelector('#system-status');
const blueprint=new Image();let blueprintReady=false;blueprint.onload=()=>{blueprintReady=true;draw()};blueprint.src='assets/submarine-layout.png';
const S=8,done=new Set(),scoreKey='posledniy-signal-top5',usedNameKey='posledniy-signal-used-names';let player={x:39,y:70},active=null,movingUntil=0,dialogKeyHandler=null,dialogCleanup=null,sessionReady=false,playerName='',runStartedAt=0,runFinished=false;
let audioCtx=null,ambientStarted=false,ambientTimer=0,lastDroneChirp=0;
function audio(){if(!audioCtx){const Engine=window.AudioContext||window.webkitAudioContext;if(!Engine)return null;audioCtx=new Engine()}if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(freq,duration=.1,volume=.03,type='sine',slide=freq,when=0){const a=audio();if(!a)return;const t=a.currentTime+when,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(1,slide),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(a.destination);o.start(t);o.stop(t+duration+.02)}
function noise(duration=.08,volume=.02,cutoff=1300,when=0){const a=audio();if(!a)return;const length=Math.ceil(a.sampleRate*duration),buffer=a.createBuffer(1,length,a.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=a.createBufferSource(),filter=a.createBiquadFilter(),g=a.createGain(),t=a.currentTime+when;filter.type='bandpass';filter.frequency.value=cutoff;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.0001,t+duration);source.buffer=buffer;source.connect(filter).connect(g).connect(a.destination);source.start(t);source.stop(t+duration+.02)}
const sfx={click(){tone(118,.07,.025,'square',74);noise(.035,.012,680)},success(){noise(.1,.055,1900);tone(1150,.18,.05,'triangle',420,.02)},error(){tone(540,.16,.045,'sawtooth',760);tone(760,.16,.035,'sawtooth',470,.13)},shot(){tone(410,.045,.018,'square',920)},hit(){tone(220,.06,.025,'square',95)},sonar(){tone(170,.38,.018,'sine',82);noise(.11,.007,240,.16)},drone(){const now=performance.now();if(now-lastDroneChirp<85)return;lastDroneChirp=now;const base=420+Math.random()*310;tone(base,.055,.018,'square',base*1.6);tone(base*1.35,.07,.014,'triangle',base*.8,.065);tone(base*.8,.05,.012,'square',base*1.25,.14)},spark(){noise(.055,.018,2700);tone(950,.035,.008,'square',440,.02)},creak(){tone(95,.22,.012,'sawtooth',55);noise(.12,.006,360)}};
function startAmbient(){const a=audio();if(!a||ambientStarted)return;ambientStarted=true;const hum=a.createOscillator(),humGain=a.createGain(),undertone=a.createOscillator(),underGain=a.createGain();hum.type='sine';hum.frequency.value=41;humGain.gain.value=.012;undertone.type='triangle';undertone.frequency.value=83;underGain.gain.value=.005;hum.connect(humGain).connect(a.destination);undertone.connect(underGain).connect(a.destination);hum.start();undertone.start();const pulse=()=>{if(Math.random()<.62)sfx.spark();else sfx.creak();if(Math.random()<.35)sfx.sonar();ambientTimer=setTimeout(pulse,4200+Math.random()*5200)};ambientTimer=setTimeout(()=>{sfx.sonar();pulse()},3200)}
const rooms=[
 {id:1,name:'РЕМОНТНЫЙ ОТСЕК',task:'power',x:31,y:67,w:14,h:8},
 {id:2,name:'ЭНЕРГООТСЕК',task:'tetris',x:48,y:49,w:13,h:8},
 {id:3,name:'ГИДРОАКУСТИКА',task:'sonar',x:84,y:66,w:15,h:8},
 {id:4,name:'КАПИТАНСКИЙ МОСТИК',task:'snake',x:88,y:38,w:13,h:8},
 {id:5,name:'КАЮТ-КОМПАНИЯ',task:'tic',x:105,y:52,w:16,h:7},
 {id:6,name:'КАМБУЗ / ОСУШЕНИЕ',task:'galaga',x:138,y:65,w:11,h:9},
 {id:7,name:'ТРЮМ СВЯЗИ',task:'mahjong',x:163,y:59,w:13,h:8}
];
// Терминалы намеренно стоят в разных местах, но их координаты постоянны:
// карта должна одинаково выглядеть во всех браузерах и после перезагрузки.
[[42,70],[57,53],[95,69],[97,44],[116,55],[145,70],[172,62]].forEach(([tx,ty],i)=>{rooms[i].tx=tx;rooms[i].ty=ty});
const corridors=[
 [38,60,1,7],[38,60,9,1],[46,55,1,6],[46,55,2,1],
 [61,53,21,1],[73,53,1,12],[73,64,17,1],[89,64,1,2],
 // Широкая развилка: вход из гидроакустики и поворот на капитанский мостик.
 [72,52,11,14],
 [81,43,1,11],[81,43,7,1],
 [95,46,1,10],[95,55,10,1],
 [121,56,9,1],[129,56,1,13],[129,68,9,1],
 [149,69,10,1],[159,63,1,7],[159,63,4,1]
];
const walk=new Set(),key=(x,y)=>x+','+y;
function add(x,y,w,h){for(let j=y;j<y+h;j++)for(let i=x;i<x+w;i++)walk.add(key(i,j));}
rooms.forEach(r=>add(r.x,r.y,r.w,r.h));corridors.forEach(c=>add(...c));
function roomAt(x,y){return rooms.find(r=>x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h)}
function say(t){message.textContent='РМ-01: '+t}
function readMemory(key){try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return []}}
function scores(){return readMemory(scoreKey).filter(s=>s&&typeof s.name==='string'&&Number.isFinite(s.time)).sort((a,b)=>a.time-b.time).slice(0,5)}
function formatTime(ms){const total=Math.max(0,Math.round(ms/1000)),m=Math.floor(total/60),s=String(total%60).padStart(2,'0');return m+':'+s}
function drawLeaderboard(){const top=scores();ctx.save();ctx.fillStyle='rgba(4,22,27,.92)';ctx.fillRect(58,126,245,132);ctx.strokeStyle='#315e61';ctx.lineWidth=2;ctx.strokeRect(58,126,245,132);ctx.fillStyle='#f7bd54';ctx.font='18px VT323';ctx.fillText('ЛУЧШИЕ ОПЕРАТОРЫ',72,148);ctx.font='16px VT323';if(top.length){top.forEach((entry,i)=>{ctx.fillStyle=i===0?'#d7fff0':'#8db8ad';ctx.fillText((i+1)+'. '+entry.name,72,171+i*16);ctx.textAlign='right';ctx.fillText(formatTime(entry.time),287,171+i*16);ctx.textAlign='left'})}else{ctx.fillStyle='#6f9a95';ctx.fillText('ОЖИДАНИЕ ПЕРВОГО ОПЕРАТОРА',72,181)}if(sessionReady&&!runFinished){ctx.fillStyle='#76e6c5';ctx.font='15px VT323';ctx.fillText('ВЫ: '+playerName+'  '+formatTime(performance.now()-runStartedAt),72,244)}ctx.restore()}
function recordScore(){if(runFinished||!sessionReady)return;runFinished=true;const result={name:playerName,time:performance.now()-runStartedAt},before=scores(),next=[...before,result].sort((a,b)=>a.time-b.time).slice(0,5),qualified=next.some(s=>s===result);localStorage.setItem(scoreKey,JSON.stringify(next));say(qualified?'ВСЕ СИСТЕМЫ ВОССТАНОВЛЕНЫ. ВЫ В ТОП-5: '+formatTime(result.time)+'.':'ВСЕ СИСТЕМЫ ВОССТАНОВЛЕНЫ. ВРЕМЯ: '+formatTime(result.time)+'.');}
function beginSession(name){playerName=name;sessionReady=true;runStartedAt=performance.now();say('Оператор '+playerName+', ведите меня по отсекам. Я отмечу терминалы и открою доступ.');dialogCleanup?.();dialogCleanup=null;dialogKeyHandler=null;dialog.close();game.focus();update()}
function showIntro(){if(dialog.open||sessionReady)return;const transcript='РМ-01: Обнаружен внешний оператор. Кто вы?';mount('ВХОДЯЩИЙ СИГНАЛ','','Введите имя: 2–14 символов. Одинаковые имена на этом устройстве не принимаются.','<div id="rm-chat" style="min-height:72px;padding:11px;border:2px solid #416c6c;background:#06151b;color:#76e6c5;font-size:22px;line-height:1.1"></div><form id="operator-form" style="margin-top:12px;display:flex;gap:8px"><input id="operator-name" maxlength="14" autocomplete="off" placeholder="ВАШЕ ИМЯ" style="min-width:0;flex:1;border:2px solid #76e6c5;background:#10242a;color:#d7fff0;padding:8px;font:20px VT323"><button style="border:2px solid #f7bd54;background:#173138;color:#f7bd54;padding:7px 11px;font:18px VT323">ОТВЕТИТЬ</button></form><div id="name-error" style="min-height:20px;color:#ef6b5d;font-size:17px"></div>');content.querySelector('.mini-copy').style.display='none';const line=content.querySelector('#rm-chat'),input=content.querySelector('#operator-name'),error=content.querySelector('#name-error');let cursor=0,typing=setInterval(()=>{line.textContent=transcript.slice(0,++cursor);if(cursor>=transcript.length)clearInterval(typing)},23);content.querySelector('#operator-form').onsubmit=e=>{e.preventDefault();const name=input.value.trim().replace(/\s+/g,' '),valid=/^[\p{L}\p{N} _-]{2,14}$/u.test(name),used=readMemory(usedNameKey),normal=name.toLocaleLowerCase('ru');if(!valid){error.textContent='ИМЯ: 2–14 БУКВ, ЦИФР ИЛИ ПРОБЕЛОВ.';return}if(used.includes(normal)){error.textContent='ЭТО ИМЯ УЖЕ ЕСТЬ В ПАМЯТИ РМ-01.';return}localStorage.setItem(usedNameKey,JSON.stringify([...used,normal]));beginSession(name)};dialogCleanup=()=>{clearInterval(typing);dialogKeyHandler=null};dialog.showModal();setTimeout(()=>input.focus(),0)}
function initialRepairLocked(x,y){const here=roomAt(player.x,player.y),there=roomAt(x,y);return done.size===0&&here?.id===1&&there?.id!==1}
function reachable(x,y){const r=roomAt(x,y);return !initialRepairLocked(x,y)&&walk.has(key(x,y))&&(!r||r.id<=done.size+1)}
const pipeSegments=[[309,536,309,482],[309,482,372,482],[372,482,372,428],[372,428,488,428],[488,428,648,428],[648,428,648,344],[648,344,704,344],[588,428,588,512],[588,512,716,512],[716,512,716,528],[760,374,760,448],[760,448,840,448],[968,448,1032,448],[1032,448,1032,544],[1032,544,1100,544],[1190,552,1272,552],[1272,552,1272,504],[1272,504,1300,504]];
function centeredPipePoint(px,py){let best=null;for(const [x1,y1,x2,y2] of pipeSegments){const dx=x2-x1,dy=y2-y1,len=dx*dx+dy*dy,t=Math.max(0,Math.min(1,((px-x1)*dx+(py-y1)*dy)/len)),x=x1+dx*t,y=y1+dy*t,d=(px-x)*(px-x)+(py-y)*(py-y);if(!best||d<best.d)best={x,y,d}}return best?[best.x,best.y]:[px,py]}
function drawAirlocks(){ctx.save();ctx.lineCap='square';ctx.lineJoin='round';const trace=()=>{ctx.beginPath();for(const [x1,y1,x2,y2] of pipeSegments){ctx.moveTo(x1,y1);ctx.lineTo(x2,y2)}};
 trace();ctx.strokeStyle='#04191d';ctx.lineWidth=54;ctx.stroke();
 trace();ctx.strokeStyle='#247c77';ctx.lineWidth=42;ctx.stroke();
 trace();ctx.strokeStyle='#9bf6df';ctx.shadowColor='#76e6c5';ctx.shadowBlur=10;ctx.lineWidth=3;ctx.stroke();ctx.restore()}
function pixel(cx,cy,x,y,w,h,color,p=3){ctx.fillStyle=color;ctx.fillRect(cx+x*p,cy+y*p,w*p,h*p)}
function drawDrone(cx,cy){ctx.save();ctx.imageSmoothingEnabled=false;const p=7,yellow='#fff04d',orange='#ff9518',redOn='#ff5c4e',blueOn='#54a9ff',redOff='#572b30',blueOff='#27364f',moving=Date.now()<movingUntil,redPhase=Math.floor(Date.now()/115)%2===0;
 // Пиксельный ремонтный модуль с присланного образца: два маяка и блок из четырёх панелей.
 pixel(cx,cy,-2,-1,1,1,moving&&redPhase?redOn:redOff,p);pixel(cx,cy,1,-1,1,1,moving&&!redPhase?blueOn:blueOff,p);
 if(moving){ctx.shadowBlur=10;ctx.shadowColor=redPhase?redOn:blueOn;pixel(cx,cy,redPhase?-2:1,-1,1,1,redPhase?redOn:blueOn,p);ctx.shadowBlur=0}
 pixel(cx,cy,-1,-1,1,1,yellow,p);pixel(cx,cy,0,-1,1,1,orange,p);pixel(cx,cy,-1,0,1,1,orange,p);pixel(cx,cy,0,0,1,1,yellow,p);ctx.restore()}
function draw(){
 const W=canvas.width,H=canvas.height;
 if(blueprintReady)ctx.drawImage(blueprint,0,0,W,H);else{ctx.fillStyle='#06151b';ctx.fillRect(0,0,W,H);return}
 ctx.fillStyle='#07191e';ctx.fillRect(1320,35,275,58);ctx.fillStyle='#f7bd54';ctx.font='32px VT323';ctx.textAlign='right';ctx.fillText('СИСТЕМЫ: '+done.size+' / 7',1575,77);ctx.textAlign='left';
 drawLeaderboard();
 [[329,584],[445,444],[763,577],[788,359],[892,465],[1174,582],[1375,524]].forEach(([x,y])=>{ctx.fillStyle='#082329';ctx.fillRect(x-15,y-15,30,30)});
 drawAirlocks();
 rooms.forEach(r=>{const fixed=done.has(r.id),needsRepair=!fixed,pulse=.72+.28*(Math.sin(Date.now()/260)+1)/2,x=r.x*S,y=r.y*S,w=r.w*S,h=r.h*S;ctx.fillStyle='rgba(5,27,32,.94)';ctx.fillRect(x+3,y+3,w-6,h-6);ctx.strokeStyle='#082329';ctx.lineWidth=8;ctx.strokeRect(x,y,w,h);ctx.save();ctx.strokeStyle=fixed?'#8dffd4':'#f7bd54';ctx.lineWidth=fixed?4:3;ctx.globalAlpha=fixed?1:pulse;if(needsRepair){ctx.shadowColor='#f7bd54';ctx.shadowBlur=8+8*pulse}ctx.strokeRect(x,y,w,h);ctx.restore();ctx.fillStyle=fixed?'#d7fff0':'#f7d28a';ctx.font='16px VT323';ctx.fillText(('0'+r.id).slice(-2),x+8,y+19);const title=r.name;let size=15;do{ctx.font=size+'px VT323';size--}while(ctx.measureText(title).width>w-16&&size>7);ctx.fillText(title,x+8,y+h-7);const tx=(r.tx+.5)*S,ty=(r.ty+.5)*S;ctx.fillStyle=fixed?'#76e6c5':'#ef6b5d';ctx.fillRect(tx-6,ty-6,12,12);ctx.strokeStyle='#e2fff2';ctx.lineWidth=2;ctx.strokeRect(tx-7,ty-7,14,14)});
 let px=(player.x+.5)*S,py=(player.y+.5)*S;if(!roomAt(player.x,player.y))[px,py]=centeredPipePoint(px,py);drawDrone(px,py);
 if(active){const tx=(active.tx+.5)*S,ty=(active.ty+.5)*S;ctx.strokeStyle='#f7bd54';ctx.lineWidth=2;ctx.strokeRect(tx-18,ty-18,36,36)}
 ctx.fillStyle='#07191e';ctx.fillRect(44,750,W-88,72);ctx.fillStyle='#e1f7ec';ctx.font='35px VT323';ctx.fillText(message.textContent,64,796);
 ctx.fillStyle='#07191e';ctx.fillRect(1370,655,225,80);ctx.fillStyle='#7fa4a5';ctx.font='18px VT323';['ДАТЧИКИ:  НОРМА','КОРПУС:   ЦЕЛ','ПИТАНИЕ:  '+done.size+' / 7'].forEach((t,i)=>ctx.fillText(t,1390,680+i*21));
}
function update(){const r=roomAt(player.x,player.y);active=r&&!done.has(r.id)&&Math.abs(player.x-r.tx)+Math.abs(player.y-r.ty)<=1?r:null;draw();}
function animateRepairFrames(){draw();requestAnimationFrame(animateRepairFrames)}
function finish(id){sfx.success();dialogCleanup?.();dialogCleanup=null;dialogKeyHandler=null;done.add(id);status.textContent='СИСТЕМЫ: '+done.size+' / 7';dialog.close();if(done.size===7)recordScore();else say('Система восстановлена. Открыт следующий шлюз.');game.focus();update()}
function mount(title,copy,hint,body){content.innerHTML='<button class="hint">?</button><h2 class="mini-title">'+title+'</h2><p class="mini-copy">'+copy+'</p><div class="hint-box"></div>'+body;content.querySelector('.hint').onclick=()=>content.querySelector('.hint-box').textContent='ПОДСКАЗКА: '+hint;}
function power(id){
 const symbols=['◉','⚙','◆','☼','✦','◈','☍','✚'],deck=[...symbols,...symbols].sort(()=>Math.random()-.5),open=Array(16).fill(false),matched=Array(16).fill(false);let first=null,scanning=false,scanTimer,scanInterval;
 mount('ЩИТ ПИТАНИЯ','Память щита: найдите восемь пар символов. После запуска сканер на 10 секунд покажет всю схему.','Нажмите «СБРОС / СКАН» в любой момент: все символы снова откроются на 10 секунд.','<div class="memory-grid">'+deck.map((_,i)=>'<button class="memory-card" data-i="'+i+'">?</button>').join('')+'</div><div class="mini-status">СКАНЕР ГОТОВ</div><button class="reset">СБРОС / СКАН: 10 СЕК.</button>');
 const cards=[...content.querySelectorAll('.memory-card')],miniStatus=content.querySelector('.mini-status');
 const draw=()=>cards.forEach((b,i)=>{const visible=scanning||open[i]||matched[i];b.textContent=visible?deck[i]:'?';b.classList.toggle('open',visible);b.classList.toggle('matched',matched[i]);b.disabled=scanning||matched[i]});
 const scan=()=>{clearTimeout(scanTimer);clearInterval(scanInterval);scanning=true;first=null;open.fill(false);let left=10;miniStatus.textContent='СКАНИРОВАНИЕ: '+left+' СЕК.';draw();scanInterval=setInterval(()=>{left--;miniStatus.textContent='СКАНИРОВАНИЕ: '+left+' СЕК.'},1000);scanTimer=setTimeout(()=>{clearInterval(scanInterval);scanning=false;miniStatus.textContent='НАЙДИТЕ ПАРЫ';draw()},10000)};
 cards.forEach(b=>b.onclick=()=>{if(scanning)return;const i=+b.dataset.i;if(open[i]||matched[i])return;sfx.click();open[i]=true;draw();if(first===null){first=i;miniStatus.textContent='ВЫБЕРИТЕ ВТОРУЮ КАРТОЧКУ';return}const other=first;first=null;if(deck[i]===deck[other]){sfx.success();matched[i]=matched[other]=true;open[i]=open[other]=false;miniStatus.textContent='ПАРА НАЙДЕНА';draw();if(matched.every(Boolean))finish(id)}else{sfx.error();miniStatus.textContent='НЕ ПАРА';setTimeout(()=>{open[i]=open[other]=false;miniStatus.textContent='НАЙДИТЕ ПАРЫ';draw()},650)}});
 content.querySelector('.reset').onclick=scan;scan();
}
function pump(id){const directions=['ВНИЗ','ВЛЕВО','ВВЕРХ','ВПРАВО'],r=[2,1,3,0];mount(id===6?'ОСУШИТЕЛЬНЫЙ НАСОС':'НАСОС № 4','Поверните каждый клапан в положение, указанное в схеме.','Цель слева направо: ВНИЗ → ВЛЕВО → ВВЕРХ → ВПРАВО. Нажатие переключает положение по этому кругу.','<div class="flow-target">ЦЕЛЬ: <b>ВНИЗ</b> → <b>ВЛЕВО</b> → <b>ВВЕРХ</b> → <b>ВПРАВО</b></div><div class="pipe-grid">'+r.map((v,i)=>'<button class="pipe-cell" data-i="'+i+'"><small>КЛАПАН '+(i+1)+'</small><strong>'+directions[v]+'</strong></button>').join('')+'</div>');content.querySelectorAll('.pipe-cell').forEach(b=>b.onclick=()=>{sfx.click();let i=+b.dataset.i;r[i]=(r[i]+1)%4;b.querySelector('strong').textContent=directions[r[i]];if(r.every((v,i)=>v===i))finish(id)})}
function tetris(id){const W=10,H=18,C=20,colors=['#76e6c5','#f7bd54','#ef6b5d','#54a9ff','#b38cff','#ff9518','#d7fff0'],shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]]];let board=Array.from({length:H},()=>Array(W).fill(null)),piece=null,score=0,timer=null,ended=false;
 mount('ЭНЕРГООТСЕК — ТЕТРИС','Соберите 1000 очков для запуска реактора. Очки начисляются только за очищенные ряды: 50 за каждый.','Стрелки: влево, вправо и вниз. Пробел поворачивает фигуру. Скорость — начальная, без ускорения.','<canvas id="tetris" width="200" height="360" aria-label="Поле Тетриса" style="display:block;width:200px;height:360px;margin:10px auto;border:2px solid #76e6c5;background:#07191e;image-rendering:pixelated"></canvas><div class="mini-status">ЭНЕРГИЯ: 0 / 1000</div>');
 const field=content.querySelector('#tetris'),g=field.getContext('2d'),statusLine=content.querySelector('.mini-status');
 const drawCell=(x,y,color)=>{g.fillStyle=color;g.fillRect(x*C+1,y*C+1,C-2,C-2);g.strokeStyle='#07191e';g.lineWidth=1;g.strokeRect(x*C+.5,y*C+.5,C-1,C-1)};
 function render(){g.fillStyle='#07191e';g.fillRect(0,0,field.width,field.height);for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(board[y][x]!==null)drawCell(x,y,board[y][x]);if(piece)piece.m.forEach((row,y)=>row.forEach((v,x)=>{if(v)drawCell(piece.x+x,piece.y+y,piece.color)}));g.strokeStyle='#76e6c5';g.lineWidth=2;g.strokeRect(1,1,198,358)}
 const fits=(m,x,y)=>m.every((row,j)=>row.every((v,i)=>!v||(x+i>=0&&x+i<W&&y+j<H&&(y+j<0||board[y+j][x+i]===null))));
 function spawn(){const m=shapes[Math.floor(Math.random()*shapes.length)].map(row=>[...row]);piece={m,x:Math.floor((W-m[0].length)/2),y:0,color:colors[Math.floor(Math.random()*colors.length)]};if(!fits(piece.m,piece.x,piece.y)){ended=true;statusLine.textContent='ПОЛЕ ПЕРЕПОЛНЕНО — НОВАЯ СМЕНА';setTimeout(()=>{if(ended){board=Array.from({length:H},()=>Array(W).fill(null));score=0;ended=false;statusLine.textContent='ЭНЕРГИЯ: 0 / 1000';spawn()}},800)}render()}
 function clearRows(){let rows=0;for(let y=H-1;y>=0;y--){if(board[y].every(Boolean)){board.splice(y,1);board.unshift(Array(W).fill(null));rows++;y++}}if(rows){score+=rows*50;statusLine.textContent='ЭНЕРГИЯ: '+score+' / 1000';if(score>=1000){ended=true;finish(id)}}}
 function lock(){if(!piece||ended)return;sfx.click();piece.m.forEach((row,y)=>row.forEach((v,x)=>{if(v&&piece.y+y>=0)board[piece.y+y][piece.x+x]=piece.color}));clearRows();if(!ended)spawn()}
 function move(dx,dy){if(piece&&!ended&&fits(piece.m,piece.x+dx,piece.y+dy)){piece.x+=dx;piece.y+=dy;render();return true}return false}
 function rotate(){if(!piece||ended)return;const m=piece.m[0].map((_,i)=>piece.m.map(row=>row[i]).reverse());for(const shift of [0,-1,1,-2,2])if(fits(m,piece.x+shift,piece.y)){piece.m=m;piece.x+=shift;render();return}}
 function tick(){if(!move(0,1))lock()}
 dialogKeyHandler=e=>{if(!['ArrowLeft','ArrowRight','ArrowDown','ArrowUp',' '].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')move(-1,0);if(e.key==='ArrowRight')move(1,0);if(e.key==='ArrowDown')tick();if(e.key===' '){sfx.click();rotate()}};
 dialogCleanup=()=>{clearInterval(timer);dialogKeyHandler=null};timer=setInterval(tick,700);spawn()
}
function snake(id){const W=14,H=18,C=18;let body=[{x:7,y:9},{x:6,y:9}],dir={x:1,y:0},next=dir,food=null,score=0,timer=null,ended=false;
 mount('КАПИТАНСКИЙ МОСТИК — ЗМЕЙКА','Соберите 20 блоков сигнала, чтобы восстановить навигацию. Стартовый хвостовой блок не засчитывается.','Стрелки меняют направление. Не врезайтесь в корпус или собственный хвост.','<canvas id="snake" width="252" height="324" aria-label="Поле Змейки" style="display:block;width:252px;height:324px;margin:10px auto;border:2px solid #76e6c5;background:#07191e;image-rendering:pixelated"></canvas><div class="mini-status">БЛОКИ: 0 / 20</div>');
 const field=content.querySelector('#snake'),g=field.getContext('2d'),statusLine=content.querySelector('.mini-status'),same=(a,b)=>a.x===b.x&&a.y===b.y;
 function spawnFood(){const free=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(!body.some(p=>p.x===x&&p.y===y))free.push({x,y});food=free[Math.floor(Math.random()*free.length)]}
 function render(){g.fillStyle='#07191e';g.fillRect(0,0,field.width,field.height);g.strokeStyle='#17373b';g.lineWidth=1;for(let x=0;x<=W;x++){g.beginPath();g.moveTo(x*C,0);g.lineTo(x*C,H*C);g.stroke()}for(let y=0;y<=H;y++){g.beginPath();g.moveTo(0,y*C);g.lineTo(W*C,y*C);g.stroke()}g.fillStyle='#ef6b5d';g.fillRect(food.x*C+3,food.y*C+3,C-6,C-6);body.forEach((p,i)=>{g.fillStyle=i?'#76e6c5':'#f7bd54';g.fillRect(p.x*C+2,p.y*C+2,C-4,C-4)});g.strokeStyle='#76e6c5';g.lineWidth=2;g.strokeRect(1,1,W*C-2,H*C-2)}
 function reset(){body=[{x:7,y:9},{x:6,y:9}];dir={x:1,y:0};next=dir;score=0;ended=false;statusLine.textContent='БЛОКИ: 0 / 20';spawnFood();render()}
 function tick(){if(ended)return;dir=next;const head={x:body[0].x+dir.x,y:body[0].y+dir.y};if(head.x<0||head.x>=W||head.y<0||head.y>=H||body.some(p=>same(p,head))){sfx.error();ended=true;statusLine.textContent='СТОЛКНОВЕНИЕ — НОВАЯ ПОПЫТКА';setTimeout(()=>{if(ended)reset()},750);return}body.unshift(head);if(same(head,food)){sfx.click();score++;statusLine.textContent='БЛОКИ: '+score+' / 20';if(score>=20){ended=true;finish(id);return}spawnFood()}else body.pop();render()}
 dialogKeyHandler=e=>{const turns={ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0},ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1}},wanted=turns[e.key];if(!wanted)return;e.preventDefault();if(wanted.x!==-dir.x||wanted.y!==-dir.y)next=wanted};
 dialogCleanup=()=>{clearInterval(timer);dialogKeyHandler=null};timer=setInterval(tick,180);spawnFood();render()
}
function sonar(id){
 let sequence=[],input=[],playing=false,timers=[];
 mount('ГИДРОАКУСТИКА','Прослушайте и повторите шесть импульсов. Нажимайте на большие кнопки «ИМПУЛЬ».','Кнопка «НОВЫЙ СИГНАЛ» каждый раз создаёт другую комбинацию. Пока индикаторы мигают, дождитесь окончания передачи.','<div class="sequence">'+[0,1,2,3].map(i=>'<button class="tone tone-'+i+'" data-i="'+i+'" aria-label="Импульс '+(i+1)+'"><small>ИМПУЛЬ</small><strong>'+(i+1)+'</strong></button>').join('')+'</div><div class="mini-status">ГОТОВ К ПЕРЕДАЧЕ</div><button class="replay">НОВЫЙ СИГНАЛ</button>');
 const tones=[...content.querySelectorAll('.tone')],miniStatus=content.querySelector('.mini-status');
 const later=(fn,ms)=>timers.push(setTimeout(fn,ms));
 function playNew(){timers.forEach(clearTimeout);timers=[];sequence=Array.from({length:6},()=>Math.floor(Math.random()*4));input=[];playing=true;tones.forEach(t=>t.classList.remove('flash'));miniStatus.textContent='СЛУШАЙТЕ…';let n=0;const next=()=>{if(n===sequence.length){playing=false;miniStatus.textContent='ПОВТОРИТЕ СИГНАЛ';return}const tone=tones[sequence[n++]];sfx.sonar();tone.classList.add('flash');later(()=>{tone.classList.remove('flash');later(next,170)},420)};later(next,350)}
 content.querySelector('.replay').onclick=playNew;
 tones.forEach(b=>b.onclick=()=>{if(playing){miniStatus.textContent='ДОЖДИТЕСЬ КОНЦА ПЕРЕДАЧИ';return}const value=+b.dataset.i;sfx.click();input.push(value);b.classList.add('flash');later(()=>b.classList.remove('flash'),160);if(value!==sequence[input.length-1]){sfx.error();input=[];miniStatus.textContent='ОШИБКА. ЗАПРОСИТЕ НОВЫЙ СИГНАЛ.'}else if(input.length===sequence.length)finish(id);else miniStatus.textContent='ПРИНЯТО: '+input.length+' / '+sequence.length});
 playNew();
}
function code(id){const answer=id===4?'731':'407';let typed='';mount(id===4?'КАПИТАНСКИЙ МОСТИК':'ТРЮМ СВЯЗИ','Введите код доступа на терминале.','Код написан в самой задаче: для мостика — номер каюты 7, палубы 3, поста 1. Для трюма — сектор 4, ячейка 0, канал 7.','<div class="choices">'+[0,1,2,3,4,7].map(n=>'<button class="choice" data-n="'+n+'">'+n+'</button>').join('')+'</div><div class="mini-status">КОД: ———</div>');content.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{sfx.click();typed+=b.dataset.n;content.querySelector('.mini-status').textContent='КОД: '+typed;if(typed.length===3){if(typed===answer)finish(id);else {sfx.error();content.querySelector('.mini-status').textContent='НЕВЕРНО. СБРОС.';typed=''}}})}
function relay(id){const correct=[2,0,3,1],input=[];mount('КАЮТ-КОМПАНИЯ','Перезапустите аварийное освещение: выберите четыре реле по порядку.','Слева направо лампы мигают: третья, первая, четвёртая, вторая.','<div class="choices">'+[0,1,2,3].map(n=>'<button class="choice" data-n="'+n+'">'+(n+1)+'</button>').join('')+'</div><div class="mini-status">ОЧЕРЕДЬ РЕЛЕ</div>');content.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{input.push(+b.dataset.n);if(input.at(-1)!==correct[input.length-1]){input.length=0;content.querySelector('.mini-status').textContent='СБРОС ЦЕПИ'}else if(input.length===4)finish(id)})}
function tic(id){const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],order=[4,0,2,6,8,1,3,5,7];let board=Array(9).fill(''),busy=false,timer=null;
 mount('КАЮТ-КОМПАНИЯ — КРЕСТИКИ-НОЛИКИ','ИИ ходит первым и просчитывает всю партию. Не дайте ему выиграть: ничья или победа восстанавливает систему.','Компьютер — X, вы — O. Он начинает с центральной клетки и ищет лучший ход.','<div class="grid" style="grid-template-columns:repeat(3,1fr);max-width:280px;margin:auto">'+board.map((_,i)=>'<button class="cell" data-i="'+i+'">·</button>').join('')+'</div><div class="mini-status">ИИ ВЫБИРАЕТ ПЕРВЫЙ ХОД…</div>');
 const cells=[...content.querySelectorAll('.cell')],statusLine=content.querySelector('.mini-status');
 function result(b){for(const [a,c,d] of lines)if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'D':''}
 function minimax(b,computer,depth){const end=result(b);if(end==='X')return 10-depth;if(end==='O')return depth-10;if(end==='D')return 0;let best=computer?-Infinity:Infinity;for(const i of order)if(!b[i]){b[i]=computer?'X':'O';const value=minimax(b,!computer,depth+1);b[i]='';best=computer?Math.max(best,value):Math.min(best,value)}return best}
 function bestMove(){let best=-Infinity,moves=[];for(const i of order)if(!board[i]){board[i]='X';const value=minimax(board,false,0);board[i]='';if(value>best){best=value;moves=[i]}else if(value===best)moves.push(i)}return moves[0]}
 function render(){cells.forEach((b,i)=>{b.textContent=board[i]||'·';b.style.color=board[i]==='X'?'#f7bd54':board[i]==='O'?'#76e6c5':'#6d9890';b.style.background=board[i]?'#153138':'#10242a'})}
 function reset(){board=Array(9).fill('');busy=true;render();statusLine.textContent='ИИ ВЫБИРАЕТ ПЕРВЫЙ ХОД…';timer=setTimeout(computer,350)}
 function finishRound(end){if(end==='X'){busy=true;statusLine.textContent='ИИ ВЫИГРАЛ. НОВАЯ ПАРТИЯ…';timer=setTimeout(reset,850)}else{busy=true;statusLine.textContent=end==='O'?'ВЫ ПОБЕДИЛИ. СИСТЕМА ЗАПУЩЕНА.':'НИЧЬЯ. СИСТЕМА ВЫДЕРЖАЛА НАГРУЗКУ.';timer=setTimeout(()=>finish(id),450)}}
 function computer(){const move=bestMove();if(move===undefined)return;board[move]='X';busy=false;render();const end=result(board);if(end)finishRound(end);else statusLine.textContent='ВАШ ХОД — O'}
 cells.forEach(b=>b.onclick=()=>{const i=+b.dataset.i;if(busy||board[i])return;sfx.click();board[i]='O';render();const end=result(board);if(end){finishRound(end);return}busy=true;statusLine.textContent='ИИ АНАЛИЗИРУЕТ…';timer=setTimeout(computer,300)});
 dialogCleanup=()=>{clearTimeout(timer)};reset()
}
function galaga(id){const W=420,H=330,LIMIT=20;let playerX=W/2,shots=[],enemies=[],started=false,ended=false,startAt=0,last=0,raf=0,completeTimer=0,swarmX=0,swarmDir=1;
 mount('КАМБУЗ / ОСУШЕНИЕ — ПЕРЕХВАТ','В отсек вошла медленная волна дронов. Уничтожьте всю пирамиду за 20 секунд до затопления.','Стрелки ← → двигают перехватчик. Пробел выпускает заряд без задержки: быстрые нажатия дают быстрый огонь. Таймер стартует только после кнопки «СТАРТ».','<canvas id="galaga" width="420" height="330" aria-label="Поле перехвата" style="display:block;width:420px;max-width:100%;height:auto;margin:10px auto;border:2px solid #76e6c5;background:#07191e;image-rendering:pixelated"></canvas><div class="mini-status">ВРЕМЯ: 20.0 · ЦЕЛИ: 57</div><button class="reset galaga-start">СТАРТ</button>');
 const field=content.querySelector('#galaga'),g=field.getContext('2d'),statusLine=content.querySelector('.mini-status'),startButton=content.querySelector('.galaga-start');
 function buildWave(){enemies=[];for(let row=0;row<6;row++){const count=7+row;for(let col=0;col<count;col++)enemies.push({x:(W-count*28)/2+col*28,y:30+row*27,alive:true})}swarmX=0;swarmDir=1}
 function render(){g.fillStyle='#07191e';g.fillRect(0,0,W,H);g.strokeStyle='#12353a';g.lineWidth=1;for(let y=18;y<H;y+=18){g.beginPath();g.moveTo(0,y);g.lineTo(W,y);g.stroke()}enemies.forEach(e=>{if(!e.alive)return;const x=e.x+swarmX,y=e.y;g.fillStyle='#ef6b5d';g.fillRect(x+3,y+4,18,12);g.fillStyle='#f7bd54';g.fillRect(x+7,y+1,10,4);g.fillStyle='#d7fff0';g.fillRect(x+5,y+8,4,3);g.fillRect(x+15,y+8,4,3);g.fillStyle='#6c272b';g.fillRect(x,y+16,24,3)});shots.forEach(s=>{g.fillStyle='#f7bd54';g.shadowColor='#f7bd54';g.shadowBlur=8;g.fillRect(s.x-2,s.y-8,4,10);g.shadowBlur=0});g.fillStyle='#76e6c5';g.fillRect(playerX-14,H-26,28,7);g.fillRect(playerX-7,H-33,14,8);g.fillStyle='#d7fff0';g.fillRect(playerX-3,H-37,6,5);g.fillStyle='#54a9ff';g.fillRect(playerX-21,H-22,8,3);g.fillRect(playerX+13,H-22,8,3);g.strokeStyle='#76e6c5';g.lineWidth=2;g.strokeRect(1,1,W-2,H-2)}
 function updateStatus(remain){const left=enemies.reduce((n,e)=>n+(e.alive?1:0),0);statusLine.textContent='ВРЕМЯ: '+Math.max(0,remain).toFixed(1)+' · ЦЕЛИ: '+left;statusLine.style.color=remain<=5?'#ef6b5d':'#f7bd54';statusLine.style.textShadow=remain<=5?'0 0 10px #ef6b5d':'none'}
 function frame(now){if(!started||ended)return;const dt=Math.min(.05,(now-last)/1000),remain=LIMIT-(now-startAt)/1000;last=now;swarmX+=swarmDir*10*dt;const living=enemies.filter(e=>e.alive);const min=Math.min(...living.map(e=>e.x+swarmX)),max=Math.max(...living.map(e=>e.x+swarmX+24));if(min<12||max>W-12)swarmDir*=-1;shots.forEach(s=>s.y-=520*dt);shots=shots.filter(s=>s.y>-12);for(const shot of shots){for(const enemy of enemies){if(enemy.alive&&shot.x>=enemy.x+swarmX&&shot.x<=enemy.x+swarmX+24&&shot.y>=enemy.y&&shot.y<=enemy.y+20){sfx.hit();enemy.alive=false;shot.y=-20;break}}}const left=enemies.reduce((n,e)=>n+(e.alive?1:0),0);updateStatus(remain);render();if(left===0){ended=true;statusLine.textContent='ВОЛНА УНИЧТОЖЕНА. ОСУШЕНИЕ ЗАПУЩЕНО.';statusLine.style.color='#76e6c5';completeTimer=setTimeout(()=>finish(id),350);return}if(remain<=0){sfx.error();ended=true;statusLine.textContent='ВРЕМЯ ВЫШЛО — ВОЛНА ВОССТАНОВЛЕНА';statusLine.style.color='#ef6b5d';startButton.textContent='ЗАНОВО';startButton.style.display='block';return}raf=requestAnimationFrame(frame)}
 function start(){cancelAnimationFrame(raf);buildWave();playerX=W/2;shots=[];started=true;ended=false;startAt=performance.now();last=startAt;startButton.style.display='none';updateStatus(LIMIT);render();raf=requestAnimationFrame(frame)}
 dialogKeyHandler=e=>{if(!started||ended)return;if(e.key==='ArrowLeft'){e.preventDefault();playerX=Math.max(22,playerX-14);render()}else if(e.key==='ArrowRight'){e.preventDefault();playerX=Math.min(W-22,playerX+14);render()}else if(e.key===' '||e.key==='Spacebar'){e.preventDefault();sfx.shot();shots.push({x:playerX,y:H-40});render()}};
 dialogCleanup=()=>{cancelAnimationFrame(raf);clearTimeout(completeTimer);dialogKeyHandler=null};startButton.onclick=start;buildWave();render()
}
function mahjong(id){const glyphs=['⚙','⚓','◉','☼','⌘','⟡','⌁','◈','♜','⚑','✶','⬡','⏣','☍','✦','⚚','⧖','⌬','⩚','✚','♒','⚛','☄','◐','⎈'];let slots=[],removed=new Set(),selected=null,locked=false,timer=0;
 [[2,8],[1,10],[0,12],[1,10],[2,8]].forEach(([start,count],y)=>{for(let x=start;x<start+count;x++)slots.push({x,y,z:0})});slots.push({x:5,y:2,z:1},{x:6,y:2,z:1});
 mount('ТРЮМ СВЯЗИ — МАДЖОНГ','Разберите помехи в канале связи: найдите и снимите 25 пар сигнальных костяшек. Времени нет — важна точность.','Костяшка доступна, когда на ней нет верхней костяшки и свободен хотя бы левый или правый край. Совпавшая пара снимается с поля.','<div id="mahjong-board" aria-label="Поле маджонга" style="position:relative;width:456px;max-width:100%;height:278px;margin:8px auto 0;background:#07191e;border:2px solid #416c6c;overflow:hidden"></div><div class="mini-status">КОСТЯШЕК: 50 · ПАР: 0 / 25</div><button class="reset mahjong-reset">НОВАЯ РАСКЛАДКА</button>');
 const board=content.querySelector('#mahjong-board'),statusLine=content.querySelector('.mini-status');
 function overlapsTop(a,b){return b.z>a.z&&Math.abs(a.x-b.x)<1&&Math.abs(a.y-b.y)<1}
 function available(i,present){const a=slots[i];if([...present].some(j=>overlapsTop(a,slots[j])))return false;const left=[...present].some(j=>slots[j].z===a.z&&slots[j].y===a.y&&slots[j].x===a.x-1),right=[...present].some(j=>slots[j].z===a.z&&slots[j].y===a.y&&slots[j].x===a.x+1);return !left||!right}
 function makeLayout(){const present=new Set(slots.map((_,i)=>i)),labels=Array.from({length:25},(_,i)=>i).sort(()=>Math.random()-.5),values=Array(50);for(const label of labels){const choices=[...present].filter(i=>available(i,present));const first=choices[Math.floor(Math.random()*choices.length)];present.delete(first);const next=[...present].filter(i=>available(i,present));const second=next[Math.floor(Math.random()*next.length)];present.delete(second);values[first]=values[second]=label}return values}
 let values=makeLayout();
 function isOpen(i){return !removed.has(i)&&available(i,new Set(slots.map((_,j)=>j).filter(j=>!removed.has(j))))}
 function render(){const pairs=removed.size/2;statusLine.textContent='КОСТЯШЕК: '+(50-removed.size)+' · ПАР: '+pairs+' / 25';board.innerHTML=slots.map((slot,i)=>{if(removed.has(i))return '';const open=isOpen(i),chosen=selected===i,label=values[i],glyph=glyphs[label],code=String(label+1).padStart(2,'0');return '<button class="mahjong-tile" data-i="'+i+'" '+(open&&!locked?'':'disabled')+' aria-label="Костяшка '+code+'" style="position:absolute;left:'+(10+slot.x*36+slot.z*3)+'px;top:'+(10+slot.y*49-slot.z*5)+'px;width:34px;height:45px;z-index:'+(10+slot.z)+';border:2px solid '+(chosen?'#f7bd54':open?'#76e6c5':'#315255')+';background:'+(chosen?'#3d3821':open?'#18353a':'#10242a')+';color:'+(open?'#d7fff0':'#587675')+';box-shadow:'+(chosen?'0 0 14px #f7bd54':'none')+';font-family:VT323;cursor:'+(open?'pointer':'default')+'"><span style="display:block;font-size:23px;line-height:22px">'+glyph+'</span><small style="display:block;font-size:10px;color:'+(open?'#f7bd54':'#476767')+'">SIG-'+code+'</small></button>'}).join('');board.querySelectorAll('.mahjong-tile').forEach(b=>b.onclick=()=>choose(+b.dataset.i))}
 function choose(i){if(locked||!isOpen(i))return;sfx.click();if(selected===null){selected=i;statusLine.textContent='ВЫБРАНА КОСТЯШКА — НАЙДИТЕ ПАРУ';render();return}if(selected===i){selected=null;render();return}if(values[selected]===values[i]){sfx.success();removed.add(selected);removed.add(i);selected=null;if(removed.size===50){statusLine.textContent='КАНАЛ ОЧИЩЕН. СВЯЗЬ ВОССТАНОВЛЕНА.';locked=true;timer=setTimeout(()=>finish(id),450);return}render()}else{sfx.error();locked=true;statusLine.textContent='НЕ ПАРА — ВЫБЕРИТЕ ДРУГУЮ КОСТЯШКУ';timer=setTimeout(()=>{selected=null;locked=false;render()},360)}}
 function reset(){clearTimeout(timer);removed=new Set();selected=null;locked=false;values=makeLayout();render()}
 content.querySelector('.mahjong-reset').onclick=reset;dialogCleanup=()=>{clearTimeout(timer);dialogKeyHandler=null};render()
}
function open(r){({power,pump,tetris,snake,sonar,code,relay,tic,galaga,mahjong})[r.task](r.id);dialog.showModal()}
window.addEventListener('keydown',e=>{audio();startAmbient();if(!sessionReady){if(dialog.open){if(e.key==='Escape'){dialogCleanup?.();dialogCleanup=null;dialog.close()}return}e.preventDefault();showIntro();return}if(dialog.open){if(e.key==='Escape'){dialogCleanup?.();dialogCleanup=null;dialogKeyHandler=null;dialog.close()}else dialogKeyHandler?.(e);return}const d={ArrowLeft:[-1,0],a:[-1,0],A:[-1,0],ArrowRight:[1,0],d:[1,0],D:[1,0],ArrowUp:[0,-1],w:[0,-1],W:[0,-1],ArrowDown:[0,1],s:[0,1],S:[0,1]}[e.key];if(d){e.preventDefault();let x=player.x+d[0],y=player.y+d[1];if(reachable(x,y)){player={x,y};movingUntil=Date.now()+360;sfx.drone()}else{sfx.error();say(initialRepairLocked(x,y)?'Сначала восстановите щит питания в этом отсеке.':'Здесь сплошная переборка или закрытый шлюз.')}update()}if((e.key==='e'||e.key==='E')&&active)open(active);if(e.key==='r'||e.key==='R')say(active?'ЦЕЛЬ: '+active.name+'. Подлетите к центральному терминалу и нажмите E.':'ЦЕЛЬ: найдите красный терминал в доступном отсеке.');});
document.querySelector('#close-game').onclick=()=>{dialogCleanup?.();dialogCleanup=null;dialogKeyHandler=null;dialog.close()};game.addEventListener('click',()=>game.focus());game.focus();update();requestAnimationFrame(animateRepairFrames);
